concurso:
  class: sfPropelRouteCollection
  options:
    model:                concurso
    module:               concurso
    prefix_path:          /concurso
    column:               con_id
    with_wildcard_routes: true

users:
  class: sfPropelRouteCollection
  options:
    model:                users
    module:               users
    prefix_path:          /users
    column:               use_id2
    with_wildcard_routes: true

statuses:
  class: sfPropelRouteCollection
  options:
    model:                statuses
    module:               statuses
    prefix_path:          /statuses
    column:               sta_id2
    with_wildcard_routes: true

puntajes:
  class: sfPropelRouteCollection
  options:
    model:                puntajes
    module:               puntajes
    prefix_path:          /puntajes
    column:               pun_id
    with_wildcard_routes: true

pages:
  class: sfPropelRouteCollection
  options:
    model:                pages
    module:               pages
    prefix_path:          /pages
    column:               pag_id2
    with_wildcard_routes: true

likes:
  class: sfPropelRouteCollection
  options:
    model:                likes
    module:               likes
    prefix_path:          /likes
    column:               lik_id2
    with_wildcard_routes: true

interest:
  class: sfPropelRouteCollection
  options:
    model:                interest
    module:               interest
    prefix_path:          /interest
    column:               int_id2
    with_wildcard_routes: true

groups:
  class: sfPropelRouteCollection
  options:
    model:                groups
    module:               groups
    prefix_path:          /groups
    column:               gro_id2
    with_wildcard_routes: true

friends:
  class: sfPropelRouteCollection
  options:
    model:                friends
    module:               friends
    prefix_path:          /friends
    column:               fri_id2
    with_wildcard_routes: true

checkins:
  class: sfPropelRouteCollection
  options:
    model:                checkins
    module:               checkins
    prefix_path:          /checkins
    column:               che_id2
    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: puntajes, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
