<?php


/**
 * This class defines the structure of the 'checkins' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 04/15/13 20:46:43
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class CheckinsTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.CheckinsTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('checkins');
		$this->setPhpName('Checkins');
		$this->setClassname('Checkins');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('CHE_ID2', 'CheId2', 'INTEGER', true, 20, null);
		$this->addForeignKey('USE_ID2', 'UseId2', 'INTEGER', 'users', 'USE_ID2', true, 20, null);
		$this->addColumn('USE_ID', 'UseId', 'VARCHAR', false, 30, null);
		$this->addColumn('CHE_ID', 'CheId', 'VARCHAR', false, 30, null);
		$this->addForeignKey('CON_ID', 'ConId', 'INTEGER', 'concurso', 'CON_ID', true, 20, null);
		$this->addColumn('CHE_NAME', 'CheName', 'VARCHAR', false, 50, null);
		$this->addColumn('CHE_PLACE', 'ChePlace', 'VARCHAR', false, 50, null);
		$this->addColumn('CHE_MESSAGE', 'CheMessage', 'VARCHAR', false, 50, null);
		$this->addColumn('CHE_LATITUDE', 'CheLatitude', 'VARCHAR', false, 50, null);
		$this->addColumn('CHE_LONGITUDE', 'CheLongitude', 'VARCHAR', false, 50, null);
		$this->addColumn('CHE_APPLICATION', 'CheApplication', 'VARCHAR', false, 50, null);
		$this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('Concurso', 'Concurso', RelationMap::MANY_TO_ONE, array('con_id' => 'con_id', ), 'RESTRICT', 'RESTRICT');
    $this->addRelation('Users', 'Users', RelationMap::MANY_TO_ONE, array('use_id2' => 'use_id2', ), 'RESTRICT', 'RESTRICT');
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
			'symfony_timestampable' => array('create_column' => 'created_at', 'update_column' => 'updated_at', ),
		);
	} // getBehaviors()

} // CheckinsTableMap
