<?php


/**
 * This class defines the structure of the 'friends' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 04/15/13 20:46:43
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class FriendsTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.FriendsTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('friends');
		$this->setPhpName('Friends');
		$this->setClassname('Friends');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('FRI_ID2', 'FriId2', 'INTEGER', true, 20, null);
		$this->addForeignKey('USE_ID2', 'UseId2', 'INTEGER', 'users', 'USE_ID2', true, 20, null);
		$this->addColumn('USE_ID', 'UseId', 'VARCHAR', false, 30, null);
		$this->addColumn('FRI_ID', 'FriId', 'VARCHAR', false, 30, null);
		$this->addForeignKey('CON_ID', 'ConId', 'INTEGER', 'concurso', 'CON_ID', true, 20, null);
		$this->addColumn('FRI_NAME', 'FriName', 'VARCHAR', false, 50, null);
		$this->addColumn('FRI_FIRST_NAME', 'FriFirstName', 'VARCHAR', false, 50, null);
		$this->addColumn('FRI_MIDDLE_NAME', 'FriMiddleName', 'VARCHAR', false, 50, null);
		$this->addColumn('FRI_LAST_NAME', 'FriLastName', 'VARCHAR', false, 50, null);
		$this->addColumn('FRI_GENDER', 'FriGender', 'VARCHAR', false, 50, null);
		$this->addColumn('FRI_LOCALE', 'FriLocale', 'VARCHAR', false, 50, null);
		$this->addColumn('FRI_LINK', 'FriLink', 'VARCHAR', false, 50, null);
		$this->addColumn('FRI_BIRTHDAY', 'FriBirthday', 'VARCHAR', false, 50, null);
		$this->addColumn('FRI_EMAIL', 'FriEmail', 'VARCHAR', false, 50, null);
		$this->addColumn('FRI_LOCATION', 'FriLocation', 'VARCHAR', false, 50, null);
		$this->addColumn('FRI_WEBSITE', 'FriWebsite', 'VARCHAR', false, 50, null);
		$this->addColumn('FRI_INVITE', 'FriInvite', 'TINYINT', false, 1, null);
		$this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('Concurso', 'Concurso', RelationMap::MANY_TO_ONE, array('con_id' => 'con_id', ), 'RESTRICT', 'RESTRICT');
    $this->addRelation('Users', 'Users', RelationMap::MANY_TO_ONE, array('use_id2' => 'use_id2', ), 'RESTRICT', 'RESTRICT');
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
			'symfony_timestampable' => array('create_column' => 'created_at', 'update_column' => 'updated_at', ),
		);
	} // getBehaviors()

} // FriendsTableMap
