<?php


/**
 * This class defines the structure of the 'pages' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 04/02/13 16:35:21
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class PagesTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.PagesTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('pages');
		$this->setPhpName('Pages');
		$this->setClassname('Pages');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('PAG_ID2', 'PagId2', 'INTEGER', true, 20, null);
		$this->addColumn('USE_ID', 'UseId', 'VARCHAR', false, 30, null);
		$this->addColumn('PAG_ID', 'PagId', 'VARCHAR', false, 30, null);
		$this->addColumn('PAG_NAME', 'PagName', 'VARCHAR', false, 50, null);
		$this->addColumn('PAG_PICTURE', 'PagPicture', 'VARCHAR', false, 50, null);
		$this->addColumn('PAG_LINK', 'PagLink', 'VARCHAR', false, 50, null);
		$this->addColumn('PAG_CATEGORY', 'PagCategory', 'VARCHAR', false, 50, null);
		$this->addColumn('PAG_LIKES', 'PagLikes', 'VARCHAR', false, 50, null);
		$this->addColumn('PAG_WEBSITE', 'PagWebsite', 'VARCHAR', false, 50, null);
		$this->addColumn('PAG_FOUNDED', 'PagFounded', 'VARCHAR', false, 50, null);
		$this->addColumn('PAG_PRODUCTS', 'PagProducts', 'VARCHAR', false, 50, null);
		$this->addColumn('PAG_CHECKINS', 'PagCheckins', 'VARCHAR', false, 50, null);
		$this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
			'symfony_timestampable' => array('create_column' => 'created_at', 'update_column' => 'updated_at', ),
		);
	} // getBehaviors()

} // PagesTableMap
