<?php


/**
 * This class defines the structure of the 'users' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 04/02/13 16:35:22
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class UsersTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.UsersTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('users');
		$this->setPhpName('Users');
		$this->setClassname('Users');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('USE_ID2', 'UseId2', 'INTEGER', true, 20, null);
		$this->addColumn('USE_ID', 'UseId', 'VARCHAR', false, 30, null);
		$this->addColumn('USE_NAME', 'UseName', 'VARCHAR', false, 50, null);
		$this->addColumn('USE_FIRST_NAME', 'UseFirstName', 'VARCHAR', false, 50, null);
		$this->addColumn('USE_MIDDLE_NAME', 'UseMiddleName', 'VARCHAR', false, 50, null);
		$this->addColumn('USE_LAST_NAME', 'UseLastName', 'VARCHAR', false, 50, null);
		$this->addColumn('USE_GENDER', 'UseGender', 'VARCHAR', false, 50, null);
		$this->addColumn('USE_LOCALE', 'UseLocale', 'VARCHAR', false, 50, null);
		$this->addColumn('USE_LINK', 'UseLink', 'VARCHAR', false, 50, null);
		$this->addColumn('USE_BIRTHDAY', 'UseBirthday', 'VARCHAR', false, 50, null);
		$this->addColumn('USE_EMAIL', 'UseEmail', 'VARCHAR', false, 50, null);
		$this->addColumn('USE_LOCATION', 'UseLocation', 'VARCHAR', false, 50, null);
		$this->addColumn('USE_WEBSITE', 'UseWebsite', 'VARCHAR', false, 50, null);
		$this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
			'symfony_timestampable' => array('create_column' => 'created_at', 'update_column' => 'updated_at', ),
		);
	} // getBehaviors()

} // UsersTableMap
