<?php

/**
 * Base class that represents a row from the 'groups' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 04/02/13 16:35:21
 *
 * @package    lib.model.om
 */
abstract class BaseGroups extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        GroupsPeer
	 */
	protected static $peer;

	/**
	 * The value for the gro_id2 field.
	 * @var        int
	 */
	protected $gro_id2;

	/**
	 * The value for the use_id field.
	 * @var        string
	 */
	protected $use_id;

	/**
	 * The value for the gro_id field.
	 * @var        string
	 */
	protected $gro_id;

	/**
	 * The value for the gro_version field.
	 * @var        string
	 */
	protected $gro_version;

	/**
	 * The value for the gro_name field.
	 * @var        string
	 */
	protected $gro_name;

	/**
	 * The value for the gro_administrator field.
	 * @var        string
	 */
	protected $gro_administrator;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'GroupsPeer';

	/**
	 * Get the [gro_id2] column value.
	 * 
	 * @return     int
	 */
	public function getGroId2()
	{
		return $this->gro_id2;
	}

	/**
	 * Get the [use_id] column value.
	 * 
	 * @return     string
	 */
	public function getUseId()
	{
		return $this->use_id;
	}

	/**
	 * Get the [gro_id] column value.
	 * 
	 * @return     string
	 */
	public function getGroId()
	{
		return $this->gro_id;
	}

	/**
	 * Get the [gro_version] column value.
	 * 
	 * @return     string
	 */
	public function getGroVersion()
	{
		return $this->gro_version;
	}

	/**
	 * Get the [gro_name] column value.
	 * 
	 * @return     string
	 */
	public function getGroName()
	{
		return $this->gro_name;
	}

	/**
	 * Get the [gro_administrator] column value.
	 * 
	 * @return     string
	 */
	public function getGroAdministrator()
	{
		return $this->gro_administrator;
	}

	/**
	 * Set the value of [gro_id2] column.
	 * 
	 * @param      int $v new value
	 * @return     Groups The current object (for fluent API support)
	 */
	public function setGroId2($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->gro_id2 !== $v) {
			$this->gro_id2 = $v;
			$this->modifiedColumns[] = GroupsPeer::GRO_ID2;
		}

		return $this;
	} // setGroId2()

	/**
	 * Set the value of [use_id] column.
	 * 
	 * @param      string $v new value
	 * @return     Groups The current object (for fluent API support)
	 */
	public function setUseId($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->use_id !== $v) {
			$this->use_id = $v;
			$this->modifiedColumns[] = GroupsPeer::USE_ID;
		}

		return $this;
	} // setUseId()

	/**
	 * Set the value of [gro_id] column.
	 * 
	 * @param      string $v new value
	 * @return     Groups The current object (for fluent API support)
	 */
	public function setGroId($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->gro_id !== $v) {
			$this->gro_id = $v;
			$this->modifiedColumns[] = GroupsPeer::GRO_ID;
		}

		return $this;
	} // setGroId()

	/**
	 * Set the value of [gro_version] column.
	 * 
	 * @param      string $v new value
	 * @return     Groups The current object (for fluent API support)
	 */
	public function setGroVersion($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->gro_version !== $v) {
			$this->gro_version = $v;
			$this->modifiedColumns[] = GroupsPeer::GRO_VERSION;
		}

		return $this;
	} // setGroVersion()

	/**
	 * Set the value of [gro_name] column.
	 * 
	 * @param      string $v new value
	 * @return     Groups The current object (for fluent API support)
	 */
	public function setGroName($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->gro_name !== $v) {
			$this->gro_name = $v;
			$this->modifiedColumns[] = GroupsPeer::GRO_NAME;
		}

		return $this;
	} // setGroName()

	/**
	 * Set the value of [gro_administrator] column.
	 * 
	 * @param      string $v new value
	 * @return     Groups The current object (for fluent API support)
	 */
	public function setGroAdministrator($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->gro_administrator !== $v) {
			$this->gro_administrator = $v;
			$this->modifiedColumns[] = GroupsPeer::GRO_ADMINISTRATOR;
		}

		return $this;
	} // setGroAdministrator()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->gro_id2 = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->use_id = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->gro_id = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->gro_version = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->gro_name = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->gro_administrator = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 6; // 6 = GroupsPeer::NUM_COLUMNS - GroupsPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Groups object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(GroupsPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = GroupsPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(GroupsPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseGroups:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				GroupsPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseGroups:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(GroupsPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseGroups:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseGroups:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				GroupsPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			if ($this->isNew() ) {
				$this->modifiedColumns[] = GroupsPeer::GRO_ID2;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = GroupsPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setGroId2($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += GroupsPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = GroupsPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = GroupsPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getGroId2();
				break;
			case 1:
				return $this->getUseId();
				break;
			case 2:
				return $this->getGroId();
				break;
			case 3:
				return $this->getGroVersion();
				break;
			case 4:
				return $this->getGroName();
				break;
			case 5:
				return $this->getGroAdministrator();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = GroupsPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getGroId2(),
			$keys[1] => $this->getUseId(),
			$keys[2] => $this->getGroId(),
			$keys[3] => $this->getGroVersion(),
			$keys[4] => $this->getGroName(),
			$keys[5] => $this->getGroAdministrator(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = GroupsPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setGroId2($value);
				break;
			case 1:
				$this->setUseId($value);
				break;
			case 2:
				$this->setGroId($value);
				break;
			case 3:
				$this->setGroVersion($value);
				break;
			case 4:
				$this->setGroName($value);
				break;
			case 5:
				$this->setGroAdministrator($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = GroupsPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setGroId2($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setUseId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setGroId($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setGroVersion($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setGroName($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setGroAdministrator($arr[$keys[5]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(GroupsPeer::DATABASE_NAME);

		if ($this->isColumnModified(GroupsPeer::GRO_ID2)) $criteria->add(GroupsPeer::GRO_ID2, $this->gro_id2);
		if ($this->isColumnModified(GroupsPeer::USE_ID)) $criteria->add(GroupsPeer::USE_ID, $this->use_id);
		if ($this->isColumnModified(GroupsPeer::GRO_ID)) $criteria->add(GroupsPeer::GRO_ID, $this->gro_id);
		if ($this->isColumnModified(GroupsPeer::GRO_VERSION)) $criteria->add(GroupsPeer::GRO_VERSION, $this->gro_version);
		if ($this->isColumnModified(GroupsPeer::GRO_NAME)) $criteria->add(GroupsPeer::GRO_NAME, $this->gro_name);
		if ($this->isColumnModified(GroupsPeer::GRO_ADMINISTRATOR)) $criteria->add(GroupsPeer::GRO_ADMINISTRATOR, $this->gro_administrator);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(GroupsPeer::DATABASE_NAME);

		$criteria->add(GroupsPeer::GRO_ID2, $this->gro_id2);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getGroId2();
	}

	/**
	 * Generic method to set the primary key (gro_id2 column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setGroId2($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Groups (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setUseId($this->use_id);

		$copyObj->setGroId($this->gro_id);

		$copyObj->setGroVersion($this->gro_version);

		$copyObj->setGroName($this->gro_name);

		$copyObj->setGroAdministrator($this->gro_administrator);


		$copyObj->setNew(true);

		$copyObj->setGroId2(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Groups Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     GroupsPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new GroupsPeer();
		}
		return self::$peer;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseGroups:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseGroups::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseGroups
