<?php

/**
 * Base class that represents a row from the 'friends' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 04/02/13 16:35:21
 *
 * @package    lib.model.om
 */
abstract class BaseFriends extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        FriendsPeer
	 */
	protected static $peer;

	/**
	 * The value for the fri_id2 field.
	 * @var        int
	 */
	protected $fri_id2;

	/**
	 * The value for the use_id field.
	 * @var        string
	 */
	protected $use_id;

	/**
	 * The value for the fri_id field.
	 * @var        string
	 */
	protected $fri_id;

	/**
	 * The value for the fri_name field.
	 * @var        string
	 */
	protected $fri_name;

	/**
	 * The value for the fri_first_name field.
	 * @var        string
	 */
	protected $fri_first_name;

	/**
	 * The value for the fri_middle_name field.
	 * @var        string
	 */
	protected $fri_middle_name;

	/**
	 * The value for the fri_last_name field.
	 * @var        string
	 */
	protected $fri_last_name;

	/**
	 * The value for the fri_gender field.
	 * @var        string
	 */
	protected $fri_gender;

	/**
	 * The value for the fri_locale field.
	 * @var        string
	 */
	protected $fri_locale;

	/**
	 * The value for the fri_link field.
	 * @var        string
	 */
	protected $fri_link;

	/**
	 * The value for the fri_birthday field.
	 * @var        string
	 */
	protected $fri_birthday;

	/**
	 * The value for the fri_email field.
	 * @var        string
	 */
	protected $fri_email;

	/**
	 * The value for the fri_location field.
	 * @var        string
	 */
	protected $fri_location;

	/**
	 * The value for the fri_website field.
	 * @var        string
	 */
	protected $fri_website;

	/**
	 * The value for the fri_invite field.
	 * @var        int
	 */
	protected $fri_invite;

	/**
	 * The value for the created_at2 field.
	 * @var        string
	 */
	protected $created_at2;

	/**
	 * The value for the updated_at2 field.
	 * @var        string
	 */
	protected $updated_at2;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'FriendsPeer';

	/**
	 * Get the [fri_id2] column value.
	 * 
	 * @return     int
	 */
	public function getFriId2()
	{
		return $this->fri_id2;
	}

	/**
	 * Get the [use_id] column value.
	 * 
	 * @return     string
	 */
	public function getUseId()
	{
		return $this->use_id;
	}

	/**
	 * Get the [fri_id] column value.
	 * 
	 * @return     string
	 */
	public function getFriId()
	{
		return $this->fri_id;
	}

	/**
	 * Get the [fri_name] column value.
	 * 
	 * @return     string
	 */
	public function getFriName()
	{
		return $this->fri_name;
	}

	/**
	 * Get the [fri_first_name] column value.
	 * 
	 * @return     string
	 */
	public function getFriFirstName()
	{
		return $this->fri_first_name;
	}

	/**
	 * Get the [fri_middle_name] column value.
	 * 
	 * @return     string
	 */
	public function getFriMiddleName()
	{
		return $this->fri_middle_name;
	}

	/**
	 * Get the [fri_last_name] column value.
	 * 
	 * @return     string
	 */
	public function getFriLastName()
	{
		return $this->fri_last_name;
	}

	/**
	 * Get the [fri_gender] column value.
	 * 
	 * @return     string
	 */
	public function getFriGender()
	{
		return $this->fri_gender;
	}

	/**
	 * Get the [fri_locale] column value.
	 * 
	 * @return     string
	 */
	public function getFriLocale()
	{
		return $this->fri_locale;
	}

	/**
	 * Get the [fri_link] column value.
	 * 
	 * @return     string
	 */
	public function getFriLink()
	{
		return $this->fri_link;
	}

	/**
	 * Get the [fri_birthday] column value.
	 * 
	 * @return     string
	 */
	public function getFriBirthday()
	{
		return $this->fri_birthday;
	}

	/**
	 * Get the [fri_email] column value.
	 * 
	 * @return     string
	 */
	public function getFriEmail()
	{
		return $this->fri_email;
	}

	/**
	 * Get the [fri_location] column value.
	 * 
	 * @return     string
	 */
	public function getFriLocation()
	{
		return $this->fri_location;
	}

	/**
	 * Get the [fri_website] column value.
	 * 
	 * @return     string
	 */
	public function getFriWebsite()
	{
		return $this->fri_website;
	}

	/**
	 * Get the [fri_invite] column value.
	 * 
	 * @return     int
	 */
	public function getFriInvite()
	{
		return $this->fri_invite;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at2] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt2($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at2 === null) {
			return null;
		}


		if ($this->created_at2 === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->created_at2);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at2, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [updated_at2] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUpdatedAt2($format = 'Y-m-d H:i:s')
	{
		if ($this->updated_at2 === null) {
			return null;
		}


		if ($this->updated_at2 === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->updated_at2);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->updated_at2, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Set the value of [fri_id2] column.
	 * 
	 * @param      int $v new value
	 * @return     Friends The current object (for fluent API support)
	 */
	public function setFriId2($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->fri_id2 !== $v) {
			$this->fri_id2 = $v;
			$this->modifiedColumns[] = FriendsPeer::FRI_ID2;
		}

		return $this;
	} // setFriId2()

	/**
	 * Set the value of [use_id] column.
	 * 
	 * @param      string $v new value
	 * @return     Friends The current object (for fluent API support)
	 */
	public function setUseId($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->use_id !== $v) {
			$this->use_id = $v;
			$this->modifiedColumns[] = FriendsPeer::USE_ID;
		}

		return $this;
	} // setUseId()

	/**
	 * Set the value of [fri_id] column.
	 * 
	 * @param      string $v new value
	 * @return     Friends The current object (for fluent API support)
	 */
	public function setFriId($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->fri_id !== $v) {
			$this->fri_id = $v;
			$this->modifiedColumns[] = FriendsPeer::FRI_ID;
		}

		return $this;
	} // setFriId()

	/**
	 * Set the value of [fri_name] column.
	 * 
	 * @param      string $v new value
	 * @return     Friends The current object (for fluent API support)
	 */
	public function setFriName($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->fri_name !== $v) {
			$this->fri_name = $v;
			$this->modifiedColumns[] = FriendsPeer::FRI_NAME;
		}

		return $this;
	} // setFriName()

	/**
	 * Set the value of [fri_first_name] column.
	 * 
	 * @param      string $v new value
	 * @return     Friends The current object (for fluent API support)
	 */
	public function setFriFirstName($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->fri_first_name !== $v) {
			$this->fri_first_name = $v;
			$this->modifiedColumns[] = FriendsPeer::FRI_FIRST_NAME;
		}

		return $this;
	} // setFriFirstName()

	/**
	 * Set the value of [fri_middle_name] column.
	 * 
	 * @param      string $v new value
	 * @return     Friends The current object (for fluent API support)
	 */
	public function setFriMiddleName($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->fri_middle_name !== $v) {
			$this->fri_middle_name = $v;
			$this->modifiedColumns[] = FriendsPeer::FRI_MIDDLE_NAME;
		}

		return $this;
	} // setFriMiddleName()

	/**
	 * Set the value of [fri_last_name] column.
	 * 
	 * @param      string $v new value
	 * @return     Friends The current object (for fluent API support)
	 */
	public function setFriLastName($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->fri_last_name !== $v) {
			$this->fri_last_name = $v;
			$this->modifiedColumns[] = FriendsPeer::FRI_LAST_NAME;
		}

		return $this;
	} // setFriLastName()

	/**
	 * Set the value of [fri_gender] column.
	 * 
	 * @param      string $v new value
	 * @return     Friends The current object (for fluent API support)
	 */
	public function setFriGender($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->fri_gender !== $v) {
			$this->fri_gender = $v;
			$this->modifiedColumns[] = FriendsPeer::FRI_GENDER;
		}

		return $this;
	} // setFriGender()

	/**
	 * Set the value of [fri_locale] column.
	 * 
	 * @param      string $v new value
	 * @return     Friends The current object (for fluent API support)
	 */
	public function setFriLocale($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->fri_locale !== $v) {
			$this->fri_locale = $v;
			$this->modifiedColumns[] = FriendsPeer::FRI_LOCALE;
		}

		return $this;
	} // setFriLocale()

	/**
	 * Set the value of [fri_link] column.
	 * 
	 * @param      string $v new value
	 * @return     Friends The current object (for fluent API support)
	 */
	public function setFriLink($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->fri_link !== $v) {
			$this->fri_link = $v;
			$this->modifiedColumns[] = FriendsPeer::FRI_LINK;
		}

		return $this;
	} // setFriLink()

	/**
	 * Set the value of [fri_birthday] column.
	 * 
	 * @param      string $v new value
	 * @return     Friends The current object (for fluent API support)
	 */
	public function setFriBirthday($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->fri_birthday !== $v) {
			$this->fri_birthday = $v;
			$this->modifiedColumns[] = FriendsPeer::FRI_BIRTHDAY;
		}

		return $this;
	} // setFriBirthday()

	/**
	 * Set the value of [fri_email] column.
	 * 
	 * @param      string $v new value
	 * @return     Friends The current object (for fluent API support)
	 */
	public function setFriEmail($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->fri_email !== $v) {
			$this->fri_email = $v;
			$this->modifiedColumns[] = FriendsPeer::FRI_EMAIL;
		}

		return $this;
	} // setFriEmail()

	/**
	 * Set the value of [fri_location] column.
	 * 
	 * @param      string $v new value
	 * @return     Friends The current object (for fluent API support)
	 */
	public function setFriLocation($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->fri_location !== $v) {
			$this->fri_location = $v;
			$this->modifiedColumns[] = FriendsPeer::FRI_LOCATION;
		}

		return $this;
	} // setFriLocation()

	/**
	 * Set the value of [fri_website] column.
	 * 
	 * @param      string $v new value
	 * @return     Friends The current object (for fluent API support)
	 */
	public function setFriWebsite($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->fri_website !== $v) {
			$this->fri_website = $v;
			$this->modifiedColumns[] = FriendsPeer::FRI_WEBSITE;
		}

		return $this;
	} // setFriWebsite()

	/**
	 * Set the value of [fri_invite] column.
	 * 
	 * @param      int $v new value
	 * @return     Friends The current object (for fluent API support)
	 */
	public function setFriInvite($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->fri_invite !== $v) {
			$this->fri_invite = $v;
			$this->modifiedColumns[] = FriendsPeer::FRI_INVITE;
		}

		return $this;
	} // setFriInvite()

	/**
	 * Sets the value of [created_at2] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Friends The current object (for fluent API support)
	 */
	public function setCreatedAt2($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at2 !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at2 !== null && $tmpDt = new DateTime($this->created_at2)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at2 = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = FriendsPeer::CREATED_AT2;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt2()

	/**
	 * Sets the value of [updated_at2] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Friends The current object (for fluent API support)
	 */
	public function setUpdatedAt2($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->updated_at2 !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->updated_at2 !== null && $tmpDt = new DateTime($this->updated_at2)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->updated_at2 = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = FriendsPeer::UPDATED_AT2;
			}
		} // if either are not null

		return $this;
	} // setUpdatedAt2()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->fri_id2 = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->use_id = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->fri_id = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->fri_name = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->fri_first_name = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->fri_middle_name = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->fri_last_name = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->fri_gender = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->fri_locale = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->fri_link = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->fri_birthday = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->fri_email = ($row[$startcol + 11] !== null) ? (string) $row[$startcol + 11] : null;
			$this->fri_location = ($row[$startcol + 12] !== null) ? (string) $row[$startcol + 12] : null;
			$this->fri_website = ($row[$startcol + 13] !== null) ? (string) $row[$startcol + 13] : null;
			$this->fri_invite = ($row[$startcol + 14] !== null) ? (int) $row[$startcol + 14] : null;
			$this->created_at2 = ($row[$startcol + 15] !== null) ? (string) $row[$startcol + 15] : null;
			$this->updated_at2 = ($row[$startcol + 16] !== null) ? (string) $row[$startcol + 16] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 17; // 17 = FriendsPeer::NUM_COLUMNS - FriendsPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Friends object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(FriendsPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = FriendsPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(FriendsPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseFriends:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				FriendsPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseFriends:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(FriendsPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseFriends:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseFriends:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				FriendsPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			if ($this->isNew() ) {
				$this->modifiedColumns[] = FriendsPeer::FRI_ID2;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = FriendsPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setFriId2($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += FriendsPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = FriendsPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = FriendsPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getFriId2();
				break;
			case 1:
				return $this->getUseId();
				break;
			case 2:
				return $this->getFriId();
				break;
			case 3:
				return $this->getFriName();
				break;
			case 4:
				return $this->getFriFirstName();
				break;
			case 5:
				return $this->getFriMiddleName();
				break;
			case 6:
				return $this->getFriLastName();
				break;
			case 7:
				return $this->getFriGender();
				break;
			case 8:
				return $this->getFriLocale();
				break;
			case 9:
				return $this->getFriLink();
				break;
			case 10:
				return $this->getFriBirthday();
				break;
			case 11:
				return $this->getFriEmail();
				break;
			case 12:
				return $this->getFriLocation();
				break;
			case 13:
				return $this->getFriWebsite();
				break;
			case 14:
				return $this->getFriInvite();
				break;
			case 15:
				return $this->getCreatedAt2();
				break;
			case 16:
				return $this->getUpdatedAt2();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = FriendsPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getFriId2(),
			$keys[1] => $this->getUseId(),
			$keys[2] => $this->getFriId(),
			$keys[3] => $this->getFriName(),
			$keys[4] => $this->getFriFirstName(),
			$keys[5] => $this->getFriMiddleName(),
			$keys[6] => $this->getFriLastName(),
			$keys[7] => $this->getFriGender(),
			$keys[8] => $this->getFriLocale(),
			$keys[9] => $this->getFriLink(),
			$keys[10] => $this->getFriBirthday(),
			$keys[11] => $this->getFriEmail(),
			$keys[12] => $this->getFriLocation(),
			$keys[13] => $this->getFriWebsite(),
			$keys[14] => $this->getFriInvite(),
			$keys[15] => $this->getCreatedAt2(),
			$keys[16] => $this->getUpdatedAt2(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = FriendsPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setFriId2($value);
				break;
			case 1:
				$this->setUseId($value);
				break;
			case 2:
				$this->setFriId($value);
				break;
			case 3:
				$this->setFriName($value);
				break;
			case 4:
				$this->setFriFirstName($value);
				break;
			case 5:
				$this->setFriMiddleName($value);
				break;
			case 6:
				$this->setFriLastName($value);
				break;
			case 7:
				$this->setFriGender($value);
				break;
			case 8:
				$this->setFriLocale($value);
				break;
			case 9:
				$this->setFriLink($value);
				break;
			case 10:
				$this->setFriBirthday($value);
				break;
			case 11:
				$this->setFriEmail($value);
				break;
			case 12:
				$this->setFriLocation($value);
				break;
			case 13:
				$this->setFriWebsite($value);
				break;
			case 14:
				$this->setFriInvite($value);
				break;
			case 15:
				$this->setCreatedAt2($value);
				break;
			case 16:
				$this->setUpdatedAt2($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = FriendsPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setFriId2($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setUseId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setFriId($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setFriName($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setFriFirstName($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setFriMiddleName($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setFriLastName($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setFriGender($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setFriLocale($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setFriLink($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setFriBirthday($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setFriEmail($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setFriLocation($arr[$keys[12]]);
		if (array_key_exists($keys[13], $arr)) $this->setFriWebsite($arr[$keys[13]]);
		if (array_key_exists($keys[14], $arr)) $this->setFriInvite($arr[$keys[14]]);
		if (array_key_exists($keys[15], $arr)) $this->setCreatedAt2($arr[$keys[15]]);
		if (array_key_exists($keys[16], $arr)) $this->setUpdatedAt2($arr[$keys[16]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(FriendsPeer::DATABASE_NAME);

		if ($this->isColumnModified(FriendsPeer::FRI_ID2)) $criteria->add(FriendsPeer::FRI_ID2, $this->fri_id2);
		if ($this->isColumnModified(FriendsPeer::USE_ID)) $criteria->add(FriendsPeer::USE_ID, $this->use_id);
		if ($this->isColumnModified(FriendsPeer::FRI_ID)) $criteria->add(FriendsPeer::FRI_ID, $this->fri_id);
		if ($this->isColumnModified(FriendsPeer::FRI_NAME)) $criteria->add(FriendsPeer::FRI_NAME, $this->fri_name);
		if ($this->isColumnModified(FriendsPeer::FRI_FIRST_NAME)) $criteria->add(FriendsPeer::FRI_FIRST_NAME, $this->fri_first_name);
		if ($this->isColumnModified(FriendsPeer::FRI_MIDDLE_NAME)) $criteria->add(FriendsPeer::FRI_MIDDLE_NAME, $this->fri_middle_name);
		if ($this->isColumnModified(FriendsPeer::FRI_LAST_NAME)) $criteria->add(FriendsPeer::FRI_LAST_NAME, $this->fri_last_name);
		if ($this->isColumnModified(FriendsPeer::FRI_GENDER)) $criteria->add(FriendsPeer::FRI_GENDER, $this->fri_gender);
		if ($this->isColumnModified(FriendsPeer::FRI_LOCALE)) $criteria->add(FriendsPeer::FRI_LOCALE, $this->fri_locale);
		if ($this->isColumnModified(FriendsPeer::FRI_LINK)) $criteria->add(FriendsPeer::FRI_LINK, $this->fri_link);
		if ($this->isColumnModified(FriendsPeer::FRI_BIRTHDAY)) $criteria->add(FriendsPeer::FRI_BIRTHDAY, $this->fri_birthday);
		if ($this->isColumnModified(FriendsPeer::FRI_EMAIL)) $criteria->add(FriendsPeer::FRI_EMAIL, $this->fri_email);
		if ($this->isColumnModified(FriendsPeer::FRI_LOCATION)) $criteria->add(FriendsPeer::FRI_LOCATION, $this->fri_location);
		if ($this->isColumnModified(FriendsPeer::FRI_WEBSITE)) $criteria->add(FriendsPeer::FRI_WEBSITE, $this->fri_website);
		if ($this->isColumnModified(FriendsPeer::FRI_INVITE)) $criteria->add(FriendsPeer::FRI_INVITE, $this->fri_invite);
		if ($this->isColumnModified(FriendsPeer::CREATED_AT2)) $criteria->add(FriendsPeer::CREATED_AT2, $this->created_at2);
		if ($this->isColumnModified(FriendsPeer::UPDATED_AT2)) $criteria->add(FriendsPeer::UPDATED_AT2, $this->updated_at2);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(FriendsPeer::DATABASE_NAME);

		$criteria->add(FriendsPeer::FRI_ID2, $this->fri_id2);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getFriId2();
	}

	/**
	 * Generic method to set the primary key (fri_id2 column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setFriId2($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Friends (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setUseId($this->use_id);

		$copyObj->setFriId($this->fri_id);

		$copyObj->setFriName($this->fri_name);

		$copyObj->setFriFirstName($this->fri_first_name);

		$copyObj->setFriMiddleName($this->fri_middle_name);

		$copyObj->setFriLastName($this->fri_last_name);

		$copyObj->setFriGender($this->fri_gender);

		$copyObj->setFriLocale($this->fri_locale);

		$copyObj->setFriLink($this->fri_link);

		$copyObj->setFriBirthday($this->fri_birthday);

		$copyObj->setFriEmail($this->fri_email);

		$copyObj->setFriLocation($this->fri_location);

		$copyObj->setFriWebsite($this->fri_website);

		$copyObj->setFriInvite($this->fri_invite);

		$copyObj->setCreatedAt2($this->created_at2);

		$copyObj->setUpdatedAt2($this->updated_at2);


		$copyObj->setNew(true);

		$copyObj->setFriId2(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Friends Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     FriendsPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new FriendsPeer();
		}
		return self::$peer;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseFriends:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseFriends::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseFriends
