<?php

/**
 * Base class that represents a row from the 'users' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 04/02/13 16:35:22
 *
 * @package    lib.model.om
 */
abstract class BaseUsers extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        UsersPeer
	 */
	protected static $peer;

	/**
	 * The value for the use_id2 field.
	 * @var        int
	 */
	protected $use_id2;

	/**
	 * The value for the use_id field.
	 * @var        string
	 */
	protected $use_id;

	/**
	 * The value for the use_name field.
	 * @var        string
	 */
	protected $use_name;

	/**
	 * The value for the use_first_name field.
	 * @var        string
	 */
	protected $use_first_name;

	/**
	 * The value for the use_middle_name field.
	 * @var        string
	 */
	protected $use_middle_name;

	/**
	 * The value for the use_last_name field.
	 * @var        string
	 */
	protected $use_last_name;

	/**
	 * The value for the use_gender field.
	 * @var        string
	 */
	protected $use_gender;

	/**
	 * The value for the use_locale field.
	 * @var        string
	 */
	protected $use_locale;

	/**
	 * The value for the use_link field.
	 * @var        string
	 */
	protected $use_link;

	/**
	 * The value for the use_birthday field.
	 * @var        string
	 */
	protected $use_birthday;

	/**
	 * The value for the use_email field.
	 * @var        string
	 */
	protected $use_email;

	/**
	 * The value for the use_location field.
	 * @var        string
	 */
	protected $use_location;

	/**
	 * The value for the use_website field.
	 * @var        string
	 */
	protected $use_website;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * The value for the updated_at field.
	 * @var        string
	 */
	protected $updated_at;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'UsersPeer';

	/**
	 * Get the [use_id2] column value.
	 * 
	 * @return     int
	 */
	public function getUseId2()
	{
		return $this->use_id2;
	}

	/**
	 * Get the [use_id] column value.
	 * 
	 * @return     string
	 */
	public function getUseId()
	{
		return $this->use_id;
	}

	/**
	 * Get the [use_name] column value.
	 * 
	 * @return     string
	 */
	public function getUseName()
	{
		return $this->use_name;
	}

	/**
	 * Get the [use_first_name] column value.
	 * 
	 * @return     string
	 */
	public function getUseFirstName()
	{
		return $this->use_first_name;
	}

	/**
	 * Get the [use_middle_name] column value.
	 * 
	 * @return     string
	 */
	public function getUseMiddleName()
	{
		return $this->use_middle_name;
	}

	/**
	 * Get the [use_last_name] column value.
	 * 
	 * @return     string
	 */
	public function getUseLastName()
	{
		return $this->use_last_name;
	}

	/**
	 * Get the [use_gender] column value.
	 * 
	 * @return     string
	 */
	public function getUseGender()
	{
		return $this->use_gender;
	}

	/**
	 * Get the [use_locale] column value.
	 * 
	 * @return     string
	 */
	public function getUseLocale()
	{
		return $this->use_locale;
	}

	/**
	 * Get the [use_link] column value.
	 * 
	 * @return     string
	 */
	public function getUseLink()
	{
		return $this->use_link;
	}

	/**
	 * Get the [use_birthday] column value.
	 * 
	 * @return     string
	 */
	public function getUseBirthday()
	{
		return $this->use_birthday;
	}

	/**
	 * Get the [use_email] column value.
	 * 
	 * @return     string
	 */
	public function getUseEmail()
	{
		return $this->use_email;
	}

	/**
	 * Get the [use_location] column value.
	 * 
	 * @return     string
	 */
	public function getUseLocation()
	{
		return $this->use_location;
	}

	/**
	 * Get the [use_website] column value.
	 * 
	 * @return     string
	 */
	public function getUseWebsite()
	{
		return $this->use_website;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}


		if ($this->created_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->created_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [updated_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUpdatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->updated_at === null) {
			return null;
		}


		if ($this->updated_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->updated_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->updated_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Set the value of [use_id2] column.
	 * 
	 * @param      int $v new value
	 * @return     Users The current object (for fluent API support)
	 */
	public function setUseId2($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->use_id2 !== $v) {
			$this->use_id2 = $v;
			$this->modifiedColumns[] = UsersPeer::USE_ID2;
		}

		return $this;
	} // setUseId2()

	/**
	 * Set the value of [use_id] column.
	 * 
	 * @param      string $v new value
	 * @return     Users The current object (for fluent API support)
	 */
	public function setUseId($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->use_id !== $v) {
			$this->use_id = $v;
			$this->modifiedColumns[] = UsersPeer::USE_ID;
		}

		return $this;
	} // setUseId()

	/**
	 * Set the value of [use_name] column.
	 * 
	 * @param      string $v new value
	 * @return     Users The current object (for fluent API support)
	 */
	public function setUseName($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->use_name !== $v) {
			$this->use_name = $v;
			$this->modifiedColumns[] = UsersPeer::USE_NAME;
		}

		return $this;
	} // setUseName()

	/**
	 * Set the value of [use_first_name] column.
	 * 
	 * @param      string $v new value
	 * @return     Users The current object (for fluent API support)
	 */
	public function setUseFirstName($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->use_first_name !== $v) {
			$this->use_first_name = $v;
			$this->modifiedColumns[] = UsersPeer::USE_FIRST_NAME;
		}

		return $this;
	} // setUseFirstName()

	/**
	 * Set the value of [use_middle_name] column.
	 * 
	 * @param      string $v new value
	 * @return     Users The current object (for fluent API support)
	 */
	public function setUseMiddleName($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->use_middle_name !== $v) {
			$this->use_middle_name = $v;
			$this->modifiedColumns[] = UsersPeer::USE_MIDDLE_NAME;
		}

		return $this;
	} // setUseMiddleName()

	/**
	 * Set the value of [use_last_name] column.
	 * 
	 * @param      string $v new value
	 * @return     Users The current object (for fluent API support)
	 */
	public function setUseLastName($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->use_last_name !== $v) {
			$this->use_last_name = $v;
			$this->modifiedColumns[] = UsersPeer::USE_LAST_NAME;
		}

		return $this;
	} // setUseLastName()

	/**
	 * Set the value of [use_gender] column.
	 * 
	 * @param      string $v new value
	 * @return     Users The current object (for fluent API support)
	 */
	public function setUseGender($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->use_gender !== $v) {
			$this->use_gender = $v;
			$this->modifiedColumns[] = UsersPeer::USE_GENDER;
		}

		return $this;
	} // setUseGender()

	/**
	 * Set the value of [use_locale] column.
	 * 
	 * @param      string $v new value
	 * @return     Users The current object (for fluent API support)
	 */
	public function setUseLocale($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->use_locale !== $v) {
			$this->use_locale = $v;
			$this->modifiedColumns[] = UsersPeer::USE_LOCALE;
		}

		return $this;
	} // setUseLocale()

	/**
	 * Set the value of [use_link] column.
	 * 
	 * @param      string $v new value
	 * @return     Users The current object (for fluent API support)
	 */
	public function setUseLink($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->use_link !== $v) {
			$this->use_link = $v;
			$this->modifiedColumns[] = UsersPeer::USE_LINK;
		}

		return $this;
	} // setUseLink()

	/**
	 * Set the value of [use_birthday] column.
	 * 
	 * @param      string $v new value
	 * @return     Users The current object (for fluent API support)
	 */
	public function setUseBirthday($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->use_birthday !== $v) {
			$this->use_birthday = $v;
			$this->modifiedColumns[] = UsersPeer::USE_BIRTHDAY;
		}

		return $this;
	} // setUseBirthday()

	/**
	 * Set the value of [use_email] column.
	 * 
	 * @param      string $v new value
	 * @return     Users The current object (for fluent API support)
	 */
	public function setUseEmail($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->use_email !== $v) {
			$this->use_email = $v;
			$this->modifiedColumns[] = UsersPeer::USE_EMAIL;
		}

		return $this;
	} // setUseEmail()

	/**
	 * Set the value of [use_location] column.
	 * 
	 * @param      string $v new value
	 * @return     Users The current object (for fluent API support)
	 */
	public function setUseLocation($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->use_location !== $v) {
			$this->use_location = $v;
			$this->modifiedColumns[] = UsersPeer::USE_LOCATION;
		}

		return $this;
	} // setUseLocation()

	/**
	 * Set the value of [use_website] column.
	 * 
	 * @param      string $v new value
	 * @return     Users The current object (for fluent API support)
	 */
	public function setUseWebsite($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->use_website !== $v) {
			$this->use_website = $v;
			$this->modifiedColumns[] = UsersPeer::USE_WEBSITE;
		}

		return $this;
	} // setUseWebsite()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Users The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = UsersPeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Sets the value of [updated_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Users The current object (for fluent API support)
	 */
	public function setUpdatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->updated_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->updated_at !== null && $tmpDt = new DateTime($this->updated_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->updated_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = UsersPeer::UPDATED_AT;
			}
		} // if either are not null

		return $this;
	} // setUpdatedAt()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->use_id2 = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->use_id = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->use_name = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->use_first_name = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->use_middle_name = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->use_last_name = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->use_gender = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->use_locale = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->use_link = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->use_birthday = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->use_email = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->use_location = ($row[$startcol + 11] !== null) ? (string) $row[$startcol + 11] : null;
			$this->use_website = ($row[$startcol + 12] !== null) ? (string) $row[$startcol + 12] : null;
			$this->created_at = ($row[$startcol + 13] !== null) ? (string) $row[$startcol + 13] : null;
			$this->updated_at = ($row[$startcol + 14] !== null) ? (string) $row[$startcol + 14] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 15; // 15 = UsersPeer::NUM_COLUMNS - UsersPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Users object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(UsersPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = UsersPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(UsersPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseUsers:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				UsersPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseUsers:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(UsersPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseUsers:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			// symfony_timestampable behavior
			if ($this->isModified() && !$this->isColumnModified(UsersPeer::UPDATED_AT))
			{
			  $this->setUpdatedAt(time());
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
				// symfony_timestampable behavior
				if (!$this->isColumnModified(UsersPeer::CREATED_AT))
				{
				  $this->setCreatedAt(time());
				}

			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseUsers:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				UsersPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			if ($this->isNew() ) {
				$this->modifiedColumns[] = UsersPeer::USE_ID2;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = UsersPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setUseId2($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += UsersPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = UsersPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = UsersPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getUseId2();
				break;
			case 1:
				return $this->getUseId();
				break;
			case 2:
				return $this->getUseName();
				break;
			case 3:
				return $this->getUseFirstName();
				break;
			case 4:
				return $this->getUseMiddleName();
				break;
			case 5:
				return $this->getUseLastName();
				break;
			case 6:
				return $this->getUseGender();
				break;
			case 7:
				return $this->getUseLocale();
				break;
			case 8:
				return $this->getUseLink();
				break;
			case 9:
				return $this->getUseBirthday();
				break;
			case 10:
				return $this->getUseEmail();
				break;
			case 11:
				return $this->getUseLocation();
				break;
			case 12:
				return $this->getUseWebsite();
				break;
			case 13:
				return $this->getCreatedAt();
				break;
			case 14:
				return $this->getUpdatedAt();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = UsersPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getUseId2(),
			$keys[1] => $this->getUseId(),
			$keys[2] => $this->getUseName(),
			$keys[3] => $this->getUseFirstName(),
			$keys[4] => $this->getUseMiddleName(),
			$keys[5] => $this->getUseLastName(),
			$keys[6] => $this->getUseGender(),
			$keys[7] => $this->getUseLocale(),
			$keys[8] => $this->getUseLink(),
			$keys[9] => $this->getUseBirthday(),
			$keys[10] => $this->getUseEmail(),
			$keys[11] => $this->getUseLocation(),
			$keys[12] => $this->getUseWebsite(),
			$keys[13] => $this->getCreatedAt(),
			$keys[14] => $this->getUpdatedAt(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = UsersPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setUseId2($value);
				break;
			case 1:
				$this->setUseId($value);
				break;
			case 2:
				$this->setUseName($value);
				break;
			case 3:
				$this->setUseFirstName($value);
				break;
			case 4:
				$this->setUseMiddleName($value);
				break;
			case 5:
				$this->setUseLastName($value);
				break;
			case 6:
				$this->setUseGender($value);
				break;
			case 7:
				$this->setUseLocale($value);
				break;
			case 8:
				$this->setUseLink($value);
				break;
			case 9:
				$this->setUseBirthday($value);
				break;
			case 10:
				$this->setUseEmail($value);
				break;
			case 11:
				$this->setUseLocation($value);
				break;
			case 12:
				$this->setUseWebsite($value);
				break;
			case 13:
				$this->setCreatedAt($value);
				break;
			case 14:
				$this->setUpdatedAt($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = UsersPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setUseId2($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setUseId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setUseName($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setUseFirstName($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setUseMiddleName($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setUseLastName($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setUseGender($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setUseLocale($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setUseLink($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setUseBirthday($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setUseEmail($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setUseLocation($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setUseWebsite($arr[$keys[12]]);
		if (array_key_exists($keys[13], $arr)) $this->setCreatedAt($arr[$keys[13]]);
		if (array_key_exists($keys[14], $arr)) $this->setUpdatedAt($arr[$keys[14]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(UsersPeer::DATABASE_NAME);

		if ($this->isColumnModified(UsersPeer::USE_ID2)) $criteria->add(UsersPeer::USE_ID2, $this->use_id2);
		if ($this->isColumnModified(UsersPeer::USE_ID)) $criteria->add(UsersPeer::USE_ID, $this->use_id);
		if ($this->isColumnModified(UsersPeer::USE_NAME)) $criteria->add(UsersPeer::USE_NAME, $this->use_name);
		if ($this->isColumnModified(UsersPeer::USE_FIRST_NAME)) $criteria->add(UsersPeer::USE_FIRST_NAME, $this->use_first_name);
		if ($this->isColumnModified(UsersPeer::USE_MIDDLE_NAME)) $criteria->add(UsersPeer::USE_MIDDLE_NAME, $this->use_middle_name);
		if ($this->isColumnModified(UsersPeer::USE_LAST_NAME)) $criteria->add(UsersPeer::USE_LAST_NAME, $this->use_last_name);
		if ($this->isColumnModified(UsersPeer::USE_GENDER)) $criteria->add(UsersPeer::USE_GENDER, $this->use_gender);
		if ($this->isColumnModified(UsersPeer::USE_LOCALE)) $criteria->add(UsersPeer::USE_LOCALE, $this->use_locale);
		if ($this->isColumnModified(UsersPeer::USE_LINK)) $criteria->add(UsersPeer::USE_LINK, $this->use_link);
		if ($this->isColumnModified(UsersPeer::USE_BIRTHDAY)) $criteria->add(UsersPeer::USE_BIRTHDAY, $this->use_birthday);
		if ($this->isColumnModified(UsersPeer::USE_EMAIL)) $criteria->add(UsersPeer::USE_EMAIL, $this->use_email);
		if ($this->isColumnModified(UsersPeer::USE_LOCATION)) $criteria->add(UsersPeer::USE_LOCATION, $this->use_location);
		if ($this->isColumnModified(UsersPeer::USE_WEBSITE)) $criteria->add(UsersPeer::USE_WEBSITE, $this->use_website);
		if ($this->isColumnModified(UsersPeer::CREATED_AT)) $criteria->add(UsersPeer::CREATED_AT, $this->created_at);
		if ($this->isColumnModified(UsersPeer::UPDATED_AT)) $criteria->add(UsersPeer::UPDATED_AT, $this->updated_at);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(UsersPeer::DATABASE_NAME);

		$criteria->add(UsersPeer::USE_ID2, $this->use_id2);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getUseId2();
	}

	/**
	 * Generic method to set the primary key (use_id2 column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setUseId2($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Users (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setUseId($this->use_id);

		$copyObj->setUseName($this->use_name);

		$copyObj->setUseFirstName($this->use_first_name);

		$copyObj->setUseMiddleName($this->use_middle_name);

		$copyObj->setUseLastName($this->use_last_name);

		$copyObj->setUseGender($this->use_gender);

		$copyObj->setUseLocale($this->use_locale);

		$copyObj->setUseLink($this->use_link);

		$copyObj->setUseBirthday($this->use_birthday);

		$copyObj->setUseEmail($this->use_email);

		$copyObj->setUseLocation($this->use_location);

		$copyObj->setUseWebsite($this->use_website);

		$copyObj->setCreatedAt($this->created_at);

		$copyObj->setUpdatedAt($this->updated_at);


		$copyObj->setNew(true);

		$copyObj->setUseId2(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Users Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     UsersPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new UsersPeer();
		}
		return self::$peer;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseUsers:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseUsers::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseUsers
