<?php

/**
 * Base class that represents a row from the 'pages' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 04/15/13 20:46:43
 *
 * @package    lib.model.om
 */
abstract class BasePages extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        PagesPeer
	 */
	protected static $peer;

	/**
	 * The value for the pag_id2 field.
	 * @var        int
	 */
	protected $pag_id2;

	/**
	 * The value for the use_id2 field.
	 * @var        int
	 */
	protected $use_id2;

	/**
	 * The value for the use_id field.
	 * @var        string
	 */
	protected $use_id;

	/**
	 * The value for the pag_id field.
	 * @var        string
	 */
	protected $pag_id;

	/**
	 * The value for the con_id field.
	 * @var        int
	 */
	protected $con_id;

	/**
	 * The value for the pag_name field.
	 * @var        string
	 */
	protected $pag_name;

	/**
	 * The value for the pag_picture field.
	 * @var        string
	 */
	protected $pag_picture;

	/**
	 * The value for the pag_link field.
	 * @var        string
	 */
	protected $pag_link;

	/**
	 * The value for the pag_category field.
	 * @var        string
	 */
	protected $pag_category;

	/**
	 * The value for the pag_likes field.
	 * @var        string
	 */
	protected $pag_likes;

	/**
	 * The value for the pag_website field.
	 * @var        string
	 */
	protected $pag_website;

	/**
	 * The value for the pag_founded field.
	 * @var        string
	 */
	protected $pag_founded;

	/**
	 * The value for the pag_products field.
	 * @var        string
	 */
	protected $pag_products;

	/**
	 * The value for the pag_checkins field.
	 * @var        string
	 */
	protected $pag_checkins;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * The value for the updated_at field.
	 * @var        string
	 */
	protected $updated_at;

	/**
	 * @var        Users
	 */
	protected $aUsers;

	/**
	 * @var        Concurso
	 */
	protected $aConcurso;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'PagesPeer';

	/**
	 * Get the [pag_id2] column value.
	 * 
	 * @return     int
	 */
	public function getPagId2()
	{
		return $this->pag_id2;
	}

	/**
	 * Get the [use_id2] column value.
	 * 
	 * @return     int
	 */
	public function getUseId2()
	{
		return $this->use_id2;
	}

	/**
	 * Get the [use_id] column value.
	 * 
	 * @return     string
	 */
	public function getUseId()
	{
		return $this->use_id;
	}

	/**
	 * Get the [pag_id] column value.
	 * 
	 * @return     string
	 */
	public function getPagId()
	{
		return $this->pag_id;
	}

	/**
	 * Get the [con_id] column value.
	 * 
	 * @return     int
	 */
	public function getConId()
	{
		return $this->con_id;
	}

	/**
	 * Get the [pag_name] column value.
	 * 
	 * @return     string
	 */
	public function getPagName()
	{
		return $this->pag_name;
	}

	/**
	 * Get the [pag_picture] column value.
	 * 
	 * @return     string
	 */
	public function getPagPicture()
	{
		return $this->pag_picture;
	}

	/**
	 * Get the [pag_link] column value.
	 * 
	 * @return     string
	 */
	public function getPagLink()
	{
		return $this->pag_link;
	}

	/**
	 * Get the [pag_category] column value.
	 * 
	 * @return     string
	 */
	public function getPagCategory()
	{
		return $this->pag_category;
	}

	/**
	 * Get the [pag_likes] column value.
	 * 
	 * @return     string
	 */
	public function getPagLikes()
	{
		return $this->pag_likes;
	}

	/**
	 * Get the [pag_website] column value.
	 * 
	 * @return     string
	 */
	public function getPagWebsite()
	{
		return $this->pag_website;
	}

	/**
	 * Get the [pag_founded] column value.
	 * 
	 * @return     string
	 */
	public function getPagFounded()
	{
		return $this->pag_founded;
	}

	/**
	 * Get the [pag_products] column value.
	 * 
	 * @return     string
	 */
	public function getPagProducts()
	{
		return $this->pag_products;
	}

	/**
	 * Get the [pag_checkins] column value.
	 * 
	 * @return     string
	 */
	public function getPagCheckins()
	{
		return $this->pag_checkins;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}


		if ($this->created_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->created_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [updated_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUpdatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->updated_at === null) {
			return null;
		}


		if ($this->updated_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->updated_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->updated_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Set the value of [pag_id2] column.
	 * 
	 * @param      int $v new value
	 * @return     Pages The current object (for fluent API support)
	 */
	public function setPagId2($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->pag_id2 !== $v) {
			$this->pag_id2 = $v;
			$this->modifiedColumns[] = PagesPeer::PAG_ID2;
		}

		return $this;
	} // setPagId2()

	/**
	 * Set the value of [use_id2] column.
	 * 
	 * @param      int $v new value
	 * @return     Pages The current object (for fluent API support)
	 */
	public function setUseId2($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->use_id2 !== $v) {
			$this->use_id2 = $v;
			$this->modifiedColumns[] = PagesPeer::USE_ID2;
		}

		if ($this->aUsers !== null && $this->aUsers->getUseId2() !== $v) {
			$this->aUsers = null;
		}

		return $this;
	} // setUseId2()

	/**
	 * Set the value of [use_id] column.
	 * 
	 * @param      string $v new value
	 * @return     Pages The current object (for fluent API support)
	 */
	public function setUseId($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->use_id !== $v) {
			$this->use_id = $v;
			$this->modifiedColumns[] = PagesPeer::USE_ID;
		}

		return $this;
	} // setUseId()

	/**
	 * Set the value of [pag_id] column.
	 * 
	 * @param      string $v new value
	 * @return     Pages The current object (for fluent API support)
	 */
	public function setPagId($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->pag_id !== $v) {
			$this->pag_id = $v;
			$this->modifiedColumns[] = PagesPeer::PAG_ID;
		}

		return $this;
	} // setPagId()

	/**
	 * Set the value of [con_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Pages The current object (for fluent API support)
	 */
	public function setConId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->con_id !== $v) {
			$this->con_id = $v;
			$this->modifiedColumns[] = PagesPeer::CON_ID;
		}

		if ($this->aConcurso !== null && $this->aConcurso->getConId() !== $v) {
			$this->aConcurso = null;
		}

		return $this;
	} // setConId()

	/**
	 * Set the value of [pag_name] column.
	 * 
	 * @param      string $v new value
	 * @return     Pages The current object (for fluent API support)
	 */
	public function setPagName($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->pag_name !== $v) {
			$this->pag_name = $v;
			$this->modifiedColumns[] = PagesPeer::PAG_NAME;
		}

		return $this;
	} // setPagName()

	/**
	 * Set the value of [pag_picture] column.
	 * 
	 * @param      string $v new value
	 * @return     Pages The current object (for fluent API support)
	 */
	public function setPagPicture($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->pag_picture !== $v) {
			$this->pag_picture = $v;
			$this->modifiedColumns[] = PagesPeer::PAG_PICTURE;
		}

		return $this;
	} // setPagPicture()

	/**
	 * Set the value of [pag_link] column.
	 * 
	 * @param      string $v new value
	 * @return     Pages The current object (for fluent API support)
	 */
	public function setPagLink($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->pag_link !== $v) {
			$this->pag_link = $v;
			$this->modifiedColumns[] = PagesPeer::PAG_LINK;
		}

		return $this;
	} // setPagLink()

	/**
	 * Set the value of [pag_category] column.
	 * 
	 * @param      string $v new value
	 * @return     Pages The current object (for fluent API support)
	 */
	public function setPagCategory($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->pag_category !== $v) {
			$this->pag_category = $v;
			$this->modifiedColumns[] = PagesPeer::PAG_CATEGORY;
		}

		return $this;
	} // setPagCategory()

	/**
	 * Set the value of [pag_likes] column.
	 * 
	 * @param      string $v new value
	 * @return     Pages The current object (for fluent API support)
	 */
	public function setPagLikes($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->pag_likes !== $v) {
			$this->pag_likes = $v;
			$this->modifiedColumns[] = PagesPeer::PAG_LIKES;
		}

		return $this;
	} // setPagLikes()

	/**
	 * Set the value of [pag_website] column.
	 * 
	 * @param      string $v new value
	 * @return     Pages The current object (for fluent API support)
	 */
	public function setPagWebsite($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->pag_website !== $v) {
			$this->pag_website = $v;
			$this->modifiedColumns[] = PagesPeer::PAG_WEBSITE;
		}

		return $this;
	} // setPagWebsite()

	/**
	 * Set the value of [pag_founded] column.
	 * 
	 * @param      string $v new value
	 * @return     Pages The current object (for fluent API support)
	 */
	public function setPagFounded($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->pag_founded !== $v) {
			$this->pag_founded = $v;
			$this->modifiedColumns[] = PagesPeer::PAG_FOUNDED;
		}

		return $this;
	} // setPagFounded()

	/**
	 * Set the value of [pag_products] column.
	 * 
	 * @param      string $v new value
	 * @return     Pages The current object (for fluent API support)
	 */
	public function setPagProducts($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->pag_products !== $v) {
			$this->pag_products = $v;
			$this->modifiedColumns[] = PagesPeer::PAG_PRODUCTS;
		}

		return $this;
	} // setPagProducts()

	/**
	 * Set the value of [pag_checkins] column.
	 * 
	 * @param      string $v new value
	 * @return     Pages The current object (for fluent API support)
	 */
	public function setPagCheckins($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->pag_checkins !== $v) {
			$this->pag_checkins = $v;
			$this->modifiedColumns[] = PagesPeer::PAG_CHECKINS;
		}

		return $this;
	} // setPagCheckins()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Pages The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = PagesPeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Sets the value of [updated_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Pages The current object (for fluent API support)
	 */
	public function setUpdatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->updated_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->updated_at !== null && $tmpDt = new DateTime($this->updated_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->updated_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = PagesPeer::UPDATED_AT;
			}
		} // if either are not null

		return $this;
	} // setUpdatedAt()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->pag_id2 = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->use_id2 = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->use_id = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->pag_id = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->con_id = ($row[$startcol + 4] !== null) ? (int) $row[$startcol + 4] : null;
			$this->pag_name = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->pag_picture = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->pag_link = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->pag_category = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->pag_likes = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->pag_website = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->pag_founded = ($row[$startcol + 11] !== null) ? (string) $row[$startcol + 11] : null;
			$this->pag_products = ($row[$startcol + 12] !== null) ? (string) $row[$startcol + 12] : null;
			$this->pag_checkins = ($row[$startcol + 13] !== null) ? (string) $row[$startcol + 13] : null;
			$this->created_at = ($row[$startcol + 14] !== null) ? (string) $row[$startcol + 14] : null;
			$this->updated_at = ($row[$startcol + 15] !== null) ? (string) $row[$startcol + 15] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 16; // 16 = PagesPeer::NUM_COLUMNS - PagesPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Pages object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aUsers !== null && $this->use_id2 !== $this->aUsers->getUseId2()) {
			$this->aUsers = null;
		}
		if ($this->aConcurso !== null && $this->con_id !== $this->aConcurso->getConId()) {
			$this->aConcurso = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(PagesPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = PagesPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aUsers = null;
			$this->aConcurso = null;
		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(PagesPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BasePages:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				PagesPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BasePages:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(PagesPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BasePages:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			// symfony_timestampable behavior
			if ($this->isModified() && !$this->isColumnModified(PagesPeer::UPDATED_AT))
			{
			  $this->setUpdatedAt(time());
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
				// symfony_timestampable behavior
				if (!$this->isColumnModified(PagesPeer::CREATED_AT))
				{
				  $this->setCreatedAt(time());
				}

			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BasePages:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				PagesPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aUsers !== null) {
				if ($this->aUsers->isModified() || $this->aUsers->isNew()) {
					$affectedRows += $this->aUsers->save($con);
				}
				$this->setUsers($this->aUsers);
			}

			if ($this->aConcurso !== null) {
				if ($this->aConcurso->isModified() || $this->aConcurso->isNew()) {
					$affectedRows += $this->aConcurso->save($con);
				}
				$this->setConcurso($this->aConcurso);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = PagesPeer::PAG_ID2;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = PagesPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setPagId2($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += PagesPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aUsers !== null) {
				if (!$this->aUsers->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aUsers->getValidationFailures());
				}
			}

			if ($this->aConcurso !== null) {
				if (!$this->aConcurso->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aConcurso->getValidationFailures());
				}
			}


			if (($retval = PagesPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = PagesPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getPagId2();
				break;
			case 1:
				return $this->getUseId2();
				break;
			case 2:
				return $this->getUseId();
				break;
			case 3:
				return $this->getPagId();
				break;
			case 4:
				return $this->getConId();
				break;
			case 5:
				return $this->getPagName();
				break;
			case 6:
				return $this->getPagPicture();
				break;
			case 7:
				return $this->getPagLink();
				break;
			case 8:
				return $this->getPagCategory();
				break;
			case 9:
				return $this->getPagLikes();
				break;
			case 10:
				return $this->getPagWebsite();
				break;
			case 11:
				return $this->getPagFounded();
				break;
			case 12:
				return $this->getPagProducts();
				break;
			case 13:
				return $this->getPagCheckins();
				break;
			case 14:
				return $this->getCreatedAt();
				break;
			case 15:
				return $this->getUpdatedAt();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = PagesPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getPagId2(),
			$keys[1] => $this->getUseId2(),
			$keys[2] => $this->getUseId(),
			$keys[3] => $this->getPagId(),
			$keys[4] => $this->getConId(),
			$keys[5] => $this->getPagName(),
			$keys[6] => $this->getPagPicture(),
			$keys[7] => $this->getPagLink(),
			$keys[8] => $this->getPagCategory(),
			$keys[9] => $this->getPagLikes(),
			$keys[10] => $this->getPagWebsite(),
			$keys[11] => $this->getPagFounded(),
			$keys[12] => $this->getPagProducts(),
			$keys[13] => $this->getPagCheckins(),
			$keys[14] => $this->getCreatedAt(),
			$keys[15] => $this->getUpdatedAt(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = PagesPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setPagId2($value);
				break;
			case 1:
				$this->setUseId2($value);
				break;
			case 2:
				$this->setUseId($value);
				break;
			case 3:
				$this->setPagId($value);
				break;
			case 4:
				$this->setConId($value);
				break;
			case 5:
				$this->setPagName($value);
				break;
			case 6:
				$this->setPagPicture($value);
				break;
			case 7:
				$this->setPagLink($value);
				break;
			case 8:
				$this->setPagCategory($value);
				break;
			case 9:
				$this->setPagLikes($value);
				break;
			case 10:
				$this->setPagWebsite($value);
				break;
			case 11:
				$this->setPagFounded($value);
				break;
			case 12:
				$this->setPagProducts($value);
				break;
			case 13:
				$this->setPagCheckins($value);
				break;
			case 14:
				$this->setCreatedAt($value);
				break;
			case 15:
				$this->setUpdatedAt($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = PagesPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setPagId2($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setUseId2($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setUseId($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setPagId($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setConId($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setPagName($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setPagPicture($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setPagLink($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setPagCategory($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setPagLikes($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setPagWebsite($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setPagFounded($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setPagProducts($arr[$keys[12]]);
		if (array_key_exists($keys[13], $arr)) $this->setPagCheckins($arr[$keys[13]]);
		if (array_key_exists($keys[14], $arr)) $this->setCreatedAt($arr[$keys[14]]);
		if (array_key_exists($keys[15], $arr)) $this->setUpdatedAt($arr[$keys[15]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(PagesPeer::DATABASE_NAME);

		if ($this->isColumnModified(PagesPeer::PAG_ID2)) $criteria->add(PagesPeer::PAG_ID2, $this->pag_id2);
		if ($this->isColumnModified(PagesPeer::USE_ID2)) $criteria->add(PagesPeer::USE_ID2, $this->use_id2);
		if ($this->isColumnModified(PagesPeer::USE_ID)) $criteria->add(PagesPeer::USE_ID, $this->use_id);
		if ($this->isColumnModified(PagesPeer::PAG_ID)) $criteria->add(PagesPeer::PAG_ID, $this->pag_id);
		if ($this->isColumnModified(PagesPeer::CON_ID)) $criteria->add(PagesPeer::CON_ID, $this->con_id);
		if ($this->isColumnModified(PagesPeer::PAG_NAME)) $criteria->add(PagesPeer::PAG_NAME, $this->pag_name);
		if ($this->isColumnModified(PagesPeer::PAG_PICTURE)) $criteria->add(PagesPeer::PAG_PICTURE, $this->pag_picture);
		if ($this->isColumnModified(PagesPeer::PAG_LINK)) $criteria->add(PagesPeer::PAG_LINK, $this->pag_link);
		if ($this->isColumnModified(PagesPeer::PAG_CATEGORY)) $criteria->add(PagesPeer::PAG_CATEGORY, $this->pag_category);
		if ($this->isColumnModified(PagesPeer::PAG_LIKES)) $criteria->add(PagesPeer::PAG_LIKES, $this->pag_likes);
		if ($this->isColumnModified(PagesPeer::PAG_WEBSITE)) $criteria->add(PagesPeer::PAG_WEBSITE, $this->pag_website);
		if ($this->isColumnModified(PagesPeer::PAG_FOUNDED)) $criteria->add(PagesPeer::PAG_FOUNDED, $this->pag_founded);
		if ($this->isColumnModified(PagesPeer::PAG_PRODUCTS)) $criteria->add(PagesPeer::PAG_PRODUCTS, $this->pag_products);
		if ($this->isColumnModified(PagesPeer::PAG_CHECKINS)) $criteria->add(PagesPeer::PAG_CHECKINS, $this->pag_checkins);
		if ($this->isColumnModified(PagesPeer::CREATED_AT)) $criteria->add(PagesPeer::CREATED_AT, $this->created_at);
		if ($this->isColumnModified(PagesPeer::UPDATED_AT)) $criteria->add(PagesPeer::UPDATED_AT, $this->updated_at);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(PagesPeer::DATABASE_NAME);

		$criteria->add(PagesPeer::PAG_ID2, $this->pag_id2);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getPagId2();
	}

	/**
	 * Generic method to set the primary key (pag_id2 column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setPagId2($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Pages (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setUseId2($this->use_id2);

		$copyObj->setUseId($this->use_id);

		$copyObj->setPagId($this->pag_id);

		$copyObj->setConId($this->con_id);

		$copyObj->setPagName($this->pag_name);

		$copyObj->setPagPicture($this->pag_picture);

		$copyObj->setPagLink($this->pag_link);

		$copyObj->setPagCategory($this->pag_category);

		$copyObj->setPagLikes($this->pag_likes);

		$copyObj->setPagWebsite($this->pag_website);

		$copyObj->setPagFounded($this->pag_founded);

		$copyObj->setPagProducts($this->pag_products);

		$copyObj->setPagCheckins($this->pag_checkins);

		$copyObj->setCreatedAt($this->created_at);

		$copyObj->setUpdatedAt($this->updated_at);


		$copyObj->setNew(true);

		$copyObj->setPagId2(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Pages Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     PagesPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new PagesPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Users object.
	 *
	 * @param      Users $v
	 * @return     Pages The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setUsers(Users $v = null)
	{
		if ($v === null) {
			$this->setUseId2(NULL);
		} else {
			$this->setUseId2($v->getUseId2());
		}

		$this->aUsers = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Users object, it will not be re-added.
		if ($v !== null) {
			$v->addPages($this);
		}

		return $this;
	}


	/**
	 * Get the associated Users object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Users The associated Users object.
	 * @throws     PropelException
	 */
	public function getUsers(PropelPDO $con = null)
	{
		if ($this->aUsers === null && ($this->use_id2 !== null)) {
			$this->aUsers = UsersPeer::retrieveByPk($this->use_id2);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aUsers->addPagess($this);
			 */
		}
		return $this->aUsers;
	}

	/**
	 * Declares an association between this object and a Concurso object.
	 *
	 * @param      Concurso $v
	 * @return     Pages The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setConcurso(Concurso $v = null)
	{
		if ($v === null) {
			$this->setConId(NULL);
		} else {
			$this->setConId($v->getConId());
		}

		$this->aConcurso = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Concurso object, it will not be re-added.
		if ($v !== null) {
			$v->addPages($this);
		}

		return $this;
	}


	/**
	 * Get the associated Concurso object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Concurso The associated Concurso object.
	 * @throws     PropelException
	 */
	public function getConcurso(PropelPDO $con = null)
	{
		if ($this->aConcurso === null && ($this->con_id !== null)) {
			$this->aConcurso = ConcursoPeer::retrieveByPk($this->con_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aConcurso->addPagess($this);
			 */
		}
		return $this->aConcurso;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

			$this->aUsers = null;
			$this->aConcurso = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BasePages:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BasePages::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BasePages
