<?php


/**
 * Skeleton subclass for representing a row from the 'concurso' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 04/15/13 20:45:35
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Concurso extends BaseConcurso {
public function __toString()
{
    return $this->getConNombre();
}
} // Concurso
