<?php


/**
 * Skeleton subclass for representing a row from the 'users' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 04/02/13 16:27:04
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Users extends BaseUsers {
public function getUsePuntos(){ 
      $c1= new Criteria();
      $c1->add(FriendsPeer::FRI_INVITE, '1');
      $c2= new Criteria();
      $c2->add(FriendsPeer::FRI_INVITE, '2');
      
        return  $this->countFriendss($c1).'-'.$this->countFriendss($c2); //$this->getConcurso(); $this->getFriendss;
    } 
} // Users
