generator:
  class: sfPropelGenerator
  param:
    model_class:           interest
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              interest
    plural:                interests
    route_prefix:          interest
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        created_at:   { label: Publicado, date_format: dd/MM/yyyy}
        use_id:       { label: Usuario }
        int_id:       { label: Interes }
        int_name:       { label: Nombre }
        int_category:       { label: Categoria }
        int_created_time:       { label: Creacion }
        pag_id:       { label: Pagina }
      list:
        title:        Lista de Me Gusta
        display:     [use_id,pag_id,int_id, int_name, int_category, int_created_time,created_at]
        batch_actions:
          #aprobar:  ~
          #rechazar: ~
          _delete:   { label: Eliminar  }
        max_per_page:   100
        object_actions:
          _edit:     { label: Editar  }
          _delete:   { label: Eliminar  }
        actions: 
          _new: { label: "Nuevo Me Gusta" }
      filter:  
        display:      [use_id,pag_id,int_id, int_name, int_category, int_created_time,created_at]
      form:    ~
      edit:
        display:  
           Informacion Me Gusta:     [use_id,pag_id,int_id, int_name, int_category, int_created_time,created_at]
        title:        Edicion Me Gusta
        actions:
          _list:        { label: Cancelar  }
          _save:        { label: Guardar  }
          _delete:      { label: Eliminar  }
      new:    
        display: 
           Informacion Me Gusta:     [use_id,pag_id,int_id, int_name, int_category, int_created_time,created_at]
        title:        Nuevo Me Gusta
        actions:
           _list:         { label: Cancelar  }
           _save:         { label: Guardar  }
           _save_and_add: { label: Guardar y crear  }